const translations = {
  en: {
    languageLabel: "Language",
    navMission: "Mission",
    navMarkets: "Markets",
    navRoutes: "Routes",
    navContact: "Contact",
    heroKicker: "Xinjiang · China · Kazakhstan · Central Asia",
    heroTitle: "Building a faster supply bridge between Chinese factories and Central Asian buyers.",
    heroText:
      "We help importers, wholesalers, and project buyers find practical product sources in China, verify factories with video evidence, and coordinate supply paths through Xinjiang's border trade network.",
    heroPrimary: "WhatsApp Inquiry",
    heroSecondary: "Explore Capability",
    scrollCue: "Scroll to see how we work",
    missionKicker: "Our Mission",
    missionTitle:
      "Central Asian buyers need speed, clarity, and proof. We turn Chinese supply options into decisions they can trust.",
    sourceTitle: "Source",
    sourceText: "Match purchase requests with suitable Chinese factories, markets, and trading sources.",
    verifyTitle: "Verify",
    verifyText: "Use product videos, factory footage, packing checks, samples, and specification reviews.",
    coordinateTitle: "Coordinate",
    coordinateText: "Compare quotation, MOQ, lead time, documents, and route options before trial orders.",
    xinjiangKicker: "Why Xinjiang",
    xinjiangTitle: "Closer to the market means faster feedback.",
    xinjiangText:
      "Xinjiang gives us a practical position for Kazakhstan and nearby Central Asian markets. It helps us combine China-wide sourcing with border route awareness and faster buyer communication.",
    businessKicker: "Main Business",
    businessTitle: "Priority categories for wholesale, distribution, and project supply.",
    autoTitle: "Auto Spare Parts",
    autoText: "Filters, brake parts, chassis, lamps, commercial vehicle parts, and fast-moving replacement SKUs.",
    buildingTitle: "Building Materials",
    buildingText: "Pipe fittings, waterproofing, hardware, electrical accessories, tools, and mixed-container supplies.",
    engineeringTitle: "Engineering Parts",
    engineeringText: "Loader, forklift, truck, generator, industrial electrical, and model-matched project components.",
    agriTitle: "Agricultural Machinery",
    agriText: "Small machinery, attachments, seasonal spare parts, repair kits, and dealer supply support.",
    lightTitle: "Light Industrial & Consumer Goods",
    lightText: "Tools, household goods, textiles, packaging goods, and wholesale items suitable for small trial orders.",
    proofKicker: "Proof Before Scale",
    proofTitle: "Factory video is not decoration. It is a trust tool.",
    proofText:
      "For overseas buyers, confidence comes from visible details: warehouse stock, packaging, testing, production lines, loading, certificates, and real communication with suppliers.",
    reduceKicker: "How We Reduce Uncertainty",
    reduceTitle: "A practical verification sequence before deeper cooperation.",
    reviewTitle: "Purchase list review",
    reviewText: "We start from product photos, specifications, quantities, target brands, destination, and price expectations.",
    comparisonTitle: "Supplier comparison",
    comparisonText: "We compare factory source, trading source, MOQ, lead time, packing, and realistic quotation range.",
    videoTitle: "Video and sample check",
    videoText: "We help prepare product video, packaging video, factory footage, and sample confirmation where needed.",
    trialTitle: "Trial order planning",
    trialText: "We coordinate next steps for sample orders, small batch orders, documents, and logistics direction.",
    routeKicker: "Border Route Network",
    routeTitle: "Xinjiang gives the work a physical anchor.",
    horgosText: "Useful for Kazakhstan-focused trial orders, buyer checks, and route comparison.",
    alashankouText: "Rail-oriented shipments, heavy goods, container planning, and project supply routes.",
    kashgarText: "Broader Central Asia exploration and southern Xinjiang market access.",
    closingKicker: "For Importers and Wholesalers",
    closingTitle: "Send us what you need. We will help you find what is realistic in China.",
    closingText:
      "Product name, photos, specification, quantity, target price, destination country, and certificate needs are enough to begin a first sourcing review.",
    contactKicker: "Contact",
    contactText: "China sourcing and B2B supply coordination for Central Asian buyers.",
    directContact: "Direct contact",
  },
};

translations.ru = {
  languageLabel: "Язык",
  navMission: "Миссия",
  navMarkets: "Товары",
  navRoutes: "Маршруты",
  navContact: "Контакты",
  heroKicker: "Синьцзян · Китай · Казахстан · Центральная Азия",
  heroTitle: "Быстрый мост поставок между китайскими заводами и покупателями Центральной Азии.",
  heroText:
    "Мы помогаем импортерам, оптовикам и проектным покупателям находить товары в Китае, проверять поставщиков через видео и координировать поставки через маршруты Синьцзяна.",
  heroPrimary: "Написать в WhatsApp",
  heroSecondary: "Наши возможности",
  scrollCue: "Прокрутите вниз",
  missionKicker: "Наша миссия",
  missionTitle: "Покупателям нужны скорость, ясность и подтверждение. Мы превращаем варианты поставок из Китая в понятные решения.",
  sourceTitle: "Поиск",
  sourceText: "Подбираем китайские заводы, рынки и торговые источники под ваш запрос.",
  verifyTitle: "Проверка",
  verifyText: "Используем видео товара, завода, упаковки, образцы и проверку характеристик.",
  coordinateTitle: "Координация",
  coordinateText: "Сравниваем цену, MOQ, сроки, документы и варианты маршрута до пробного заказа.",
  xinjiangKicker: "Почему Синьцзян",
  xinjiangTitle: "Ближе к рынку значит быстрее получать обратную связь.",
  xinjiangText: "Синьцзян удобен для Казахстана и соседних рынков. Мы соединяем поиск по всему Китаю с пониманием приграничной логистики.",
  businessKicker: "Основные направления",
  businessTitle: "Категории для опта, дистрибуции и проектных поставок.",
  autoTitle: "Автозапчасти",
  autoText: "Фильтры, тормозные детали, ходовая, фары, запчасти для коммерческого транспорта и ходовые SKU.",
  buildingTitle: "Стройматериалы",
  buildingText: "Фитинги, гидроизоляция, крепеж, электрика, инструменты и смешанные контейнеры.",
  engineeringTitle: "Запчасти для техники",
  engineeringText: "Погрузчики, вилочные погрузчики, грузовики, генераторы, электрика и детали по модели.",
  agriTitle: "Сельхозтехника",
  agriText: "Малая техника, навесное оборудование, сезонные запчасти и ремонтные комплекты.",
  lightTitle: "Товары легкой промышленности",
  lightText: "Инструменты, товары для дома, текстиль, упаковка и оптовые товары для пробных заказов.",
  proofKicker: "Доказательство перед масштабом",
  proofTitle: "Видео завода — это инструмент доверия.",
  proofText: "Покупатель видит склад, упаковку, тестирование, производство, загрузку, сертификаты и реальную связь с поставщиком.",
  reduceKicker: "Как мы снижаем неопределенность",
  reduceTitle: "Практичная последовательность проверки перед сотрудничеством.",
  reviewTitle: "Анализ заявки",
  reviewText: "Начинаем с фото, характеристик, количества, брендов, страны назначения и ожидаемой цены.",
  comparisonTitle: "Сравнение поставщиков",
  comparisonText: "Сравниваем завод, торговый источник, MOQ, сроки, упаковку и реалистичный диапазон цены.",
  videoTitle: "Видео и образцы",
  videoText: "Помогаем подготовить видео товара, упаковки, завода и подтверждение образцов.",
  trialTitle: "Пробный заказ",
  trialText: "Координируем образцы, малые партии, документы и направление логистики.",
  routeKicker: "Приграничные маршруты",
  routeTitle: "Синьцзян дает физическую опору работе.",
  horgosText: "Подходит для заказов в Казахстан, проверки покупателей и сравнения маршрутов.",
  alashankouText: "Железнодорожные отправки, тяжелые грузы, контейнеры и проектные поставки.",
  kashgarText: "Шире для Центральной Азии и рынков южного Синьцзяна.",
  closingKicker: "Для импортеров и оптовиков",
  closingTitle: "Отправьте запрос. Мы покажем, что реально найти в Китае.",
  closingText: "Название товара, фото, характеристики, количество, целевая цена, страна назначения и сертификаты достаточны для начала.",
  contactKicker: "Контакты",
  contactText: "Поиск товаров в Китае и B2B-координация для покупателей Центральной Азии.",
  directContact: "Прямой контакт",
};

translations.zh = {
  languageLabel: "语言",
  navMission: "使命",
  navMarkets: "主营",
  navRoutes: "口岸",
  navContact: "联系",
  heroKicker: "新疆 · 中国 · 哈萨克斯坦 · 中亚",
  heroTitle: "连接中国工厂与中亚买家的高效供应桥梁。",
  heroText: "我们帮助进口商、批发商和项目采购方在中国寻找合适货源，通过工厂视频核验供应商，并结合新疆口岸路线推进供应方案。",
  heroPrimary: "WhatsApp 咨询",
  heroSecondary: "查看能力",
  scrollCue: "向下了解我们如何工作",
  missionKicker: "我们的使命",
  missionTitle: "中亚买家需要速度、清晰度和可信证据。我们把中国供应链选择变成可以判断的采购方案。",
  sourceTitle: "找货源",
  sourceText: "根据采购需求匹配中国工厂、市场档口和贸易资源。",
  verifyTitle: "做核验",
  verifyText: "用产品视频、工厂实拍、包装检查、样品和规格核对建立信任。",
  coordinateTitle: "促成合作",
  coordinateText: "在试单前比较报价、MOQ、交期、文件和路线方案。",
  xinjiangKicker: "为什么是新疆",
  xinjiangTitle: "离市场越近，反馈越快。",
  xinjiangText: "新疆适合从哈萨克斯坦及周边中亚市场切入，把全国供应链资源和边境路线认知结合起来。",
  businessKicker: "主营业务",
  businessTitle: "面向批发、分销和项目采购的优先品类。",
  autoTitle: "汽车配件",
  autoText: "滤清器、刹车件、底盘件、灯具、商用车配件和高频易损件。",
  buildingTitle: "建材与五金",
  buildingText: "管件、防水材料、五金工具、电气辅材、施工耗材和混装供应。",
  engineeringTitle: "工程设备配件",
  engineeringText: "装载机、叉车、卡车、发电机、工业电气件和按型号匹配的项目配件。",
  agriTitle: "农机与备件",
  agriText: "小型农机、属具、季节性备件、维修件包和经销商供货支持。",
  lightTitle: "轻工与消费品",
  lightText: "工具、家居用品、纺织品、包装用品和适合小批量试单的批发商品。",
  proofKicker: "先验证，再放量",
  proofTitle: "工厂视频不是装饰，是信任工具。",
  proofText: "海外买家需要看到库存、包装、测试、产线、装柜、证书和真实供应商沟通细节。",
  reduceKicker: "我们如何降低不确定性",
  reduceTitle: "正式合作前的可执行核验流程。",
  reviewTitle: "采购清单分析",
  reviewText: "从产品图片、规格、数量、目标品牌、目的国和价格预期开始。",
  comparisonTitle: "供应商比较",
  comparisonText: "比较工厂、贸易商、MOQ、交期、包装和真实报价区间。",
  videoTitle: "视频与样品核验",
  videoText: "协助准备产品、包装、工厂实拍和样品确认。",
  trialTitle: "试单规划",
  trialText: "协调样品、小批量订单、文件和物流方向。",
  routeKicker: "边境口岸网络",
  routeTitle: "新疆让供应链工作有现实支点。",
  horgosText: "适合哈萨克斯坦方向试单、买家沟通和路线对比。",
  alashankouText: "适合铁路、重货、整柜和项目供应。",
  kashgarText: "适合探索更广的中亚市场和南疆资源。",
  closingKicker: "面向进口商和批发商",
  closingTitle: "把你的需求发给我们，我们帮你判断中国能否实现。",
  closingText: "产品名称、图片、规格、数量、目标价、目的国和证书要求即可开始初步评估。",
  contactKicker: "联系",
  contactText: "面向中亚买家的中国货源匹配和 B2B 供应协调。",
  directContact: "直接联系",
};

translations.kk = {
  ...translations.ru,
  languageLabel: "Тіл",
  navMission: "Миссия",
  navMarkets: "Бағыттар",
  navRoutes: "Маршруттар",
  navContact: "Байланыс",
  heroKicker: "Шыңжаң · Қытай · Қазақстан · Орталық Азия",
  heroTitle: "Қытай зауыттары мен Орталық Азия сатып алушылары арасындағы жылдам жеткізу көпірі.",
  heroText: "Біз импорттаушыларға және көтерме сатып алушыларға Қытайдан тауар табуға, зауытты видео арқылы тексеруге және Шыңжаң бағыттары арқылы жеткізу шешімін дайындауға көмектесеміз.",
  heroPrimary: "WhatsApp арқылы жазу",
  heroSecondary: "Мүмкіндіктерді көру",
  businessTitle: "Көтерме сауда, дистрибуция және жобалық жеткізуге арналған негізгі санаттар.",
  routeTitle: "Шыңжаң жұмысымызға нақты логистикалық тірек береді.",
  closingTitle: "Қажет тауарды жіберіңіз. Біз Қытайдан нақты не табуға болатынын көрсетеміз.",
  contactText: "Орталық Азия сатып алушыларына Қытайдан тауар іздеу және B2B жеткізуді үйлестіру.",
};

translations.uz = {
  ...translations.ru,
  languageLabel: "Til",
  navMission: "Missiya",
  navMarkets: "Yo'nalishlar",
  navRoutes: "Yo'nalishlar",
  navContact: "Aloqa",
  heroKicker: "Shinjon · Xitoy · Qozog'iston · Markaziy Osiyo",
  heroTitle: "Xitoy zavodlari va Markaziy Osiyo xaridorlari o'rtasida tezkor ta'minot ko'prigi.",
  heroText: "Biz importerlar va ulgurji xaridorlarga Xitoydan mos mahsulot topish, zavodni video orqali tekshirish va Shinjon yo'nalishlari orqali ta'minot rejasini tuzishda yordam beramiz.",
  heroPrimary: "WhatsApp orqali bog'lanish",
  heroSecondary: "Imkoniyatlarni ko'rish",
  businessTitle: "Ulgurji savdo, distribyutsiya va loyiha ta'minoti uchun ustuvor mahsulot toifalari.",
  closingTitle: "Kerakli mahsulotni yuboring. Biz Xitoyda real variantlarni topishga yordam beramiz.",
  contactText: "Markaziy Osiyo xaridorlari uchun Xitoydan mahsulot izlash va B2B ta'minotni muvofiqlashtirish.",
};

translations.ky = {
  ...translations.ru,
  languageLabel: "Тил",
  navMission: "Миссия",
  navMarkets: "Багыттар",
  navRoutes: "Маршруттар",
  navContact: "Байланыш",
  heroKicker: "Шинжаң · Кытай · Казакстан · Борбор Азия",
  heroTitle: "Кытай заводдору менен Борбор Азия сатып алуучуларынын ортосунда тез камсыздоо көпүрөсү.",
  heroText: "Биз импортчуларга жана дүң сатып алуучуларга Кытайдан товар табууга, заводду видео аркылуу текшерүүгө жана Шинжаң маршруттары менен камсыздоо планын түзүүгө жардам беребиз.",
  heroPrimary: "WhatsApp аркылуу байланышуу",
  heroSecondary: "Мүмкүнчүлүктөрдү көрүү",
  businessTitle: "Дүң соода, дистрибуция жана долбоордук камсыздоо үчүн негизги товар категориялары.",
  closingTitle: "Керектүү товарды жөнөтүңүз. Биз Кытайдан реалдуу варианттарды табууга жардам беребиз.",
  contactText: "Борбор Азия сатып алуучулары үчүн Кытайдан товар издөө жана B2B камсыздоону координациялоо.",
};

translations.tr = {
  ...translations.en,
  languageLabel: "Dil",
  navMission: "Misyon",
  navMarkets: "Alanlar",
  navRoutes: "Rotalar",
  navContact: "İletişim",
  heroKicker: "Sincan · Çin · Kazakistan · Orta Asya",
  heroTitle: "Çin fabrikaları ile Orta Asya alıcıları arasında hızlı bir tedarik köprüsü kuruyoruz.",
  heroText: "İthalatçılara, toptancılara ve proje alıcılarına Çin'de uygun ürün kaynağı bulma, fabrikaları video ile doğrulama ve Sincan güzergahları üzerinden tedarik planlama konusunda yardımcı oluyoruz.",
  heroPrimary: "WhatsApp ile iletişim",
  heroSecondary: "Kabiliyetleri gör",
  missionTitle: "Orta Asya alıcıları hız, netlik ve kanıt ister. Çin tedarik seçeneklerini güvenilir kararlara dönüştürüyoruz.",
  businessTitle: "Toptan satış, dağıtım ve proje tedariki için öncelikli ürün kategorileri.",
  closingTitle: "İhtiyacınızı gönderin. Çin'de gerçekçi olan seçenekleri bulmanıza yardımcı olalım.",
  contactText: "Orta Asya alıcıları için Çin kaynak bulma ve B2B tedarik koordinasyonu.",
};

translations.ar = {
  ...translations.en,
  languageLabel: "اللغة",
  navMission: "المهمة",
  navMarkets: "المنتجات",
  navRoutes: "المسارات",
  navContact: "اتصال",
  heroKicker: "شينجيانغ · الصين · كازاخستان · آسيا الوسطى",
  heroTitle: "نبني جسرا أسرع بين المصانع الصينية والمشترين في آسيا الوسطى.",
  heroText: "نساعد المستوردين وتجار الجملة ومشتري المشاريع على إيجاد مصادر مناسبة في الصين، والتحقق من المصانع بالفيديو، وتنسيق خيارات التوريد عبر مسارات شينجيانغ.",
  heroPrimary: "تواصل عبر واتساب",
  heroSecondary: "عرض القدرات",
  scrollCue: "مرر للأسفل لمعرفة طريقة العمل",
  missionTitle: "يحتاج المشترون إلى السرعة والوضوح والدليل. نحول خيارات التوريد الصينية إلى قرارات موثوقة.",
  businessTitle: "فئات رئيسية للتجارة بالجملة والتوزيع وتوريد المشاريع.",
  closingTitle: "أرسلوا طلبكم، وسنساعدكم في معرفة الخيارات الواقعية في الصين.",
  contactText: "البحث عن مصادر في الصين وتنسيق توريد B2B للمشترين في آسيا الوسطى.",
  directContact: "اتصال مباشر",
};

const select = document.querySelector("#languageSelect");

function applyLanguage(lang) {
  const pack = translations[lang] || translations.en;
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (pack[key]) node.textContent = pack[key];
  });
  localStorage.setItem("siteLanguage", lang);
}

const saved = localStorage.getItem("siteLanguage");
const browserLang = navigator.language?.slice(0, 2);
const initial = saved || (translations[browserLang] ? browserLang : "en");
select.value = initial;
applyLanguage(initial);
select.addEventListener("change", (event) => applyLanguage(event.target.value));
